
notifications:
  email:
    on_success: never
    on_failure: never

git:
  depth: 20
  #submodules_depth: 100

language:
  - cpp

#os: linux
#dist: trusty
#
#compiler:
#  - clang
#  - gcc
#
#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    - llvm-toolchain-trusty
#    packages:
#    - cmake
#    - gcc-6
#    - g++-6
#    - clang-3.7

#matrix:
#  include:
#    - os: windows
#
#    - os: linux
#      compiler: gcc
#    - os: linux
#      compiler: clang
#
#    - os: osx
#      osx_image: xcode12
#    - os: osx
#      osx_image: xcode11
#    - os: osx
#      osx_image: xcode10

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang

#before_script:
#  - cmake -B ./build -S ./Projects -DCMAKE_BUILD_TYPE=Release
#script:     
#  - cmake --build ./build --config Release --target coolprop-download
#  - cmake --build ./build --config Release --target ExternalMediaLib

before_script:
  - mkdir build
  - pushd build
  - cmake ../Projects -DCMAKE_BUILD_TYPE=Release
  - popd
script:
  - cmake --build build --config Release --target ExternalMediaLib
  - cmake --build build --config Release --target coolprop_comparisons
